# Generated by Django 4.0.6 on 2025-02-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0004_dailymob_dailymobitem_dailymobemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='created_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
