# Generated by Django 4.0.6 on 2025-02-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_dailymob_crew_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected')], default=1),
        ),
    ]
