# Generated by Django 4.0.6 on 2025-02-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0008_dailymob_approved_by_dailymob_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailymob',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected'), (6, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='dailymobemployee',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected'), (6, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='dailymobitem',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected'), (6, 'Deleted')], default=1),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected'), (6, 'Deleted')], default=1),
        ),
    ]
