# Generated by Django 4.0.6 on 2025-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0009_dailymob_deleted_by_dailymob_deleted_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymobemployee',
            name='is_own_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymobemployee',
            name='own_vehicle_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
