# Generated by Django 4.0.6 on 2025-04-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0101_dailyemployee_is_own_vehicle_and_more'),
        ('mobile', '0010_dailymobemployee_is_own_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMobDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docType', models.IntegerField(choices=[(1, 'Maps'), (2, 'Pictures'), (3, 'Material Backup')], default=1)),
                ('docName', models.CharField(blank=True, max_length=200, null=True)),
                ('docDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.FileField(null=True, upload_to='dailys')),
                ('Status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Sent'), (3, 'Pending'), (4, 'Approved'), (5, 'Rejected'), (6, 'Deleted')], default=1)),
                ('isAuthorized', models.BooleanField(default=False)),
                ('authorized_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('DailyID', models.ForeignKey(db_column='DailyID', on_delete=django.db.models.deletion.CASCADE, to='mobile.dailymob')),
                ('autorizedID', models.ForeignKey(blank=True, db_column='autorizedID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.authorizedbilling')),
            ],
        ),
    ]
