# Generated by Django 4.0.6 on 2025-06-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0011_dailymobdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='daily_Status',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'Work in Progress')], default=1),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_comments',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_zone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
