# Generated by Django 4.0.6 on 2025-06-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0012_dailymob_daily_status_dailymob_daily_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymob',
            name='daily_Status',
            field=models.IntegerField(choices=[(1, 'Work in Progress'), (2, 'Done')], default=1),
        ),
    ]
