# Generated by Django 4.0.6 on 2025-06-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0013_alter_dailymob_daily_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymob',
            name='daily_Status',
            field=models.IntegerField(blank=True, choices=[(1, 'Work in Progress'), (2, 'Done')], default=1, null=True),
        ),
    ]
