# Generated by Django 4.0.6 on 2025-06-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0014_alter_dailymob_daily_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='daily_production',
            field=models.BooleanField(default=False),
        ),
    ]
