# Generated by Django 4.0.6 on 2025-06-30 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0015_dailymob_daily_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='daily_cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_fd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_nfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_rtb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailymob',
            name='daily_wp',
            field=models.BooleanField(default=False),
        ),
    ]
