# Generated by Django 4.0.6 on 2026-01-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0016_dailymob_daily_cd_dailymob_daily_fd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymob',
            name='daily_rtb_pep',
            field=models.BooleanField(default=False),
        ),
    ]
