# Generated by Django 4.0.6 on 2025-02-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0096_alter_woadjustment_estimatenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='approved_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='crew_by_user',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='sent_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
