# Generated by Django 4.0.6 on 2025-02-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0097_daily_approved_by_daily_approved_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
