# Generated by Django 4.0.6 on 2025-02-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0098_employee_is_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='mobile_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
