# Generated by Django 4.0.6 on 2025-03-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0099_daily_mobile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
