# Generated by Django 4.0.6 on 2025-04-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0100_item_is_new_item_updatedby_item_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyemployee',
            name='is_own_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailyemployee',
            name='own_vehicle_pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
