# Generated by Django 4.0.6 on 2025-04-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0102_dailydocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='employee/signature'),
        ),
    ]
