# Generated by Django 4.0.6 on 2025-05-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0103_employee_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoiceFile',
            field=models.FileField(null=True, upload_to='InvoiceWO'),
        ),
    ]
