# Generated by Django 4.0.6 on 2025-08-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0104_workorder_invoicefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='woestimate',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='currentStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='nextStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill')], max_length=20, null=True),
        ),
    ]
