# Generated by Django 4.0.6 on 2025-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0105_woestimate_comment_alter_workorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='mobile_sup_comments',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='mobile_tech_comments',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
