# Generated by Django 4.0.6 on 2025-10-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0106_daily_mobile_sup_comments_daily_mobile_tech_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='downloaded_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
