# Generated by Django 4.0.6 on 2026-01-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0107_daily_download_date_daily_downloaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='Status',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill'), ('8', 'RTB / Pending External Production')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='currentStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill'), ('8', 'RTB / Pending External Production')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wostatuslog',
            name='nextStatus',
            field=models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill'), ('8', 'RTB / Pending External Production')], max_length=20, null=True),
        ),
    ]
