# Generated by Django 4.0.6 on 2026-01-27 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0108_alter_workorder_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='daily_cd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_fd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_nfs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_rtb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_rtb_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daily',
            name='daily_wp',
            field=models.BooleanField(default=False),
        ),
    ]
