# Generated by Django 4.0.6 on 2026-03-13 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0109_daily_daily_cd_daily_daily_fd_daily_daily_nfs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedWorkOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prismID', models.CharField(max_length=200)),
                ('workOrderId', models.CharField(max_length=200)),
                ('PO', models.CharField(max_length=200)),
                ('POAmount', models.CharField(blank=True, max_length=200, null=True)),
                ('ConstType', models.CharField(blank=True, max_length=200, null=True)),
                ('ConstCoordinator', models.CharField(blank=True, max_length=200, null=True)),
                ('WorkOrderDate', models.CharField(blank=True, max_length=200, null=True)),
                ('EstCompletion', models.CharField(blank=True, max_length=200, null=True)),
                ('IssuedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('JobName', models.CharField(blank=True, max_length=200, null=True)),
                ('JobAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('SiteContactName', models.CharField(blank=True, max_length=200, null=True)),
                ('SitePhoneNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('Comments', models.CharField(blank=True, max_length=200, null=True)),
                ('Status', models.CharField(blank=True, choices=[('1', 'Not Started'), ('2', 'Work in Progress'), ('3', 'Pending Docs'), ('4', 'Pending Revised WO'), ('5', 'Invoiced'), ('6', 'Transferred'), ('7', 'Ready to Bill'), ('8', 'RTB / Pending External Production')], max_length=20, null=True)),
                ('CloseDate', models.CharField(blank=True, max_length=200, null=True)),
                ('UploadDate', models.CharField(blank=True, max_length=200, null=True)),
                ('UserName', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('linkedOrder', models.CharField(blank=True, max_length=600, null=True)),
                ('pre_invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceFile', models.FileField(null=True, upload_to='InvoiceWO')),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.locations')),
                ('WCSup', models.ForeignKey(blank=True, db_column='WCSup', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workOrder.employee')),
            ],
            options={
                'unique_together': {('prismID', 'workOrderId', 'PO')},
            },
        ),
    ]
