# Generated by Django 4.0.6 on 2026-03-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0110_deletedworkorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletedworkorders',
            name='deletedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='deletedworkorders',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
