# Generated by Django 4.0.6 on 2026-03-31 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0111_deletedworkorders_deletedby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedInternalPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poNumber', models.IntegerField(blank=True, null=True)),
                ('vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.CharField(blank=True, max_length=600, null=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('total', models.CharField(blank=True, max_length=20, null=True)),
                ('nonBillable', models.BooleanField(default=False)),
                ('isAmountRounded', models.BooleanField(default=True)),
                ('estimate', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.IntegerField(choices=[(1, 'Open'), (2, 'Estimated'), (3, 'Invoiced'), (4, 'Removed')], default=1)),
                ('receipt', models.FileField(null=True, upload_to='po')),
                ('transfer_date', models.DateTimeField(blank=True, null=True)),
                ('transferBy', models.CharField(blank=True, max_length=60, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('createdBy', models.CharField(blank=True, max_length=60, null=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('deletedBy', models.CharField(blank=True, max_length=60, null=True)),
                ('pickupEmployee_d', models.ForeignKey(blank=True, db_column='pickupEmployee_d', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickupEmployee_d', to='workOrder.employee')),
                ('supervisor_d', models.ForeignKey(blank=True, db_column='supervisor_d', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_d', to='workOrder.employee')),
                ('transferFromPO_d', models.ForeignKey(blank=True, db_column='transferFromPO_d', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferFromPO_d', to='workOrder.workorder')),
                ('transferToPO_d', models.ForeignKey(blank=True, db_column='transferToPO_d', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transferToPO_d', to='workOrder.workorder')),
                ('woID_d', models.ForeignKey(db_column='woID_d', on_delete=django.db.models.deletion.CASCADE, related_name='woID_d', to='workOrder.workorder')),
            ],
            options={
                'unique_together': {('id', 'woID_d')},
            },
        ),
    ]
