# Generated by Django 4.0.6 on 2026-05-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0112_deletedinternalpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='invoices',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
