# Generated by Django 4.0.6 on 2026-06-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workOrder', '0113_internalpo_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalpo',
            name='updatedBy',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='internalpo',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
